HelpmeHunter/HelpmeHunter.Presentacion.Landing/ViewModels/Cuenta/EmpresaVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta
{
    public class EmpresaVM
    {
        [Required(ErrorMessage = "Ingresa la razon social de tu empresa")]
        public string RazonSocial { get; set; }

        [Required(ErrorMessage = "Ingresa el RUC de tu empresa")]
        public string RUC { get; set; }

        [Required(ErrorMessage = "Selecciona el sector al que pertenece tu empresa")]
        public int IdSector { get; set; }

        public string WebSite { get; set; }

        [Required(ErrorMessage = "Ingresa el télefono de tu empresa")]
        public string Telefono { get; set; }

        public string Anexo { get; set; }

        [Required(ErrorMessage = "Ingresa tu celular")]
        public string Celular { get; set; }

        [Required(ErrorMessage = "Selecciona tu país")]
        public int? IdPais { get; set; }

        [Required(ErrorMessage = "Selecciona el país de tu empresa")]
        public int? IdPaisEmpresa { get; set; }

        [Required(ErrorMessage = "Ingresa tus nombres")]
        public string Nombres { get; set; }

        [Required(ErrorMessage = "Ingresa tus apellidos")]
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "Ingresa tu correo corporativo")]
        [EmailAddress(ErrorMessage = "No es un correo válido")]
        [DataType(DataType.EmailAddress)]
        public string CorreoCorporativo { get; set; }

        [Required(ErrorMessage = "Selecciona tu puesto actual")]
        public string PuestoActual { get; set; }

        public SelectList Sectores { get; set; }

        public SelectList Paises { get; set; }
    }
}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/ViewModels/Cuenta/IndexVM.cs
using System.ComponentModel.DataAnnotations;

namespace HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta
{
    public class IndexVM
    {
        [Required(ErrorMessage = "Ingresa tu correo")]
        [EmailAddress(ErrorMessage = "No es un correo válido")]
        [DataType(DataType.EmailAddress)]
        public string Correo { get; set; }

        [Required(ErrorMessage = "Ingresa tu clave")]
        [DataType(DataType.Password)]
        public string Clave { get; set; }

        public bool EsEmpresa { get; set; }
    }
}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/ViewModels/Cuenta/ProfesionalVM.cs
using System.ComponentModel.DataAnnotations;

namespace HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta
{
    public class ProfesionalVM
    {
        [Required(ErrorMessage = "Selecciona una razón de empleo")]
        public int IdRazonEmpleo { get; set; }

        public int[] IdSector { get; set; }

        public int[] IdArea { get; set; }

    }
}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Controllers/CuentaController.cs
using HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta;
using HelpmeHunter.Utilitarios;
using HelpmeHunter.Utilitarios.Mvc;
using System.Web.Mvc;
using System.Linq;
using HelpmeHunter.Modelo.Repositorios;

namespace HelpmeHunter.Presentacion.Landing.Controllers
{
    public class CuentaController : BasicController
    {
        private readonly RepositorioSector repositorioSector;
        private readonly RepositorioPais repositorioPais;
        private readonly RepositorioPuesto repositorioPuesto;

        public CuentaController(RepositorioSector repositorioSector, RepositorioPais repositorioPais, RepositorioPuesto repositorioPuesto)
        {
            this.repositorioSector = repositorioSector;
            this.repositorioPais = repositorioPais;
            this.repositorioPuesto = repositorioPuesto;
        }

        public ActionResult Index()
        {
            return View(ObtenerViewModel<IndexVM>() ?? new IndexVM());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(IndexVM viewModel)
        {
            if (ModelState.IsValid)
            {

            }

            GuardarViewModel(viewModel);
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Empresa()
        {
            var viewModel = ObtenerViewModel<EmpresaVM>() ?? new EmpresaVM();
            viewModel.Sectores = repositorioSector.Listar().ToSelectList("IdSector", "Nombre");
            viewModel.Paises = repositorioPais.Listar().ToSelectList("IdPais", "Nombre");

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Empresa(EmpresaVM viewModel)
        {
            if (ModelState.IsValid)
            {
                var idPuesto = repositorioPuesto.Obtener(p => p.Nombre == viewModel.PuestoActual).IdPuesto;
            }

            GuardarViewModel(viewModel);
            return RedirectToAction(nameof(Empresa));
        }

        public ActionResult Profesional()
        {
            return View();
        }

        public ActionResult Consultor()
        {
            return View();
        }

        public JsonResult ListarPuestos(string query)
        {
            query = string.IsNullOrWhiteSpace(query) ? string.Empty : query.Trim();
            return Json(repositorioPuesto
                .Listar(p => query == "" || p.Nombre.Contains(query))
                .Select(p => p.Nombre)
                .ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Controllers/HomeController.cs
using System.Web.Mvc;

namespace HelpmeHunter.Presentacion.Landing.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Acerca()
        {
            return View();
        }

        public ActionResult Contacto()
        {
            return View();
        }

        public ActionResult Servicios()
        {
            return View();
        }

        public ActionResult Trabajo()
        {
            return View();
        }
    }
}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Views/Cuenta/Empresa.cshtml
@model HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta.EmpresaVM

@{
    ViewBag.Title = "Empresa";
    Layout = "~/Views/Shared/_CuentaLayout.cshtml";
}

@section Styles {
    <link href="~/remark/plugins/select2/select2.min09a2.css" rel="stylesheet" />
    <link href="~/remark/plugins/bootstrap-select/bootstrap-select.min09a2.css" rel="stylesheet" />
    <link href="~/remark/plugins/formatter-js/masks.min09a2.css" rel="stylesheet" />
    <link href="~/remark/plugins/typeahead-js/typeahead.min09a2.css" rel="stylesheet" />
    <style>
        .page-content {
            max-width: 900px;
            width: 100%;
        }
    </style>
}

<h4 class="text-left">Completa los datos de tu empresa</h4>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="st-label">Razón social</label>
                @Html.TextBoxFor(m => m.RazonSocial, new { @class = "form-control", @placeholder = "Ingresa la razón social de tu empresa" })
                @Html.ValidationMessageFor(m => m.RazonSocial)
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">RUC</label>
                @Html.TextBoxFor(m => m.RUC, new { @class = "form-control input-number", @maxlength = 11, @placeholder = "Ingresa en RUC de tu empresa" })
                @Html.ValidationMessageFor(m => m.RUC)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">Sector</label>
                @Html.DropDownListFor(m => m.IdSector, Model.Sectores, new { @class = "form-control", @data_plugin = "select2" })
                @Html.ValidationMessageFor(m => m.IdSector)
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">Website</label>
                @Html.TextBoxFor(m => m.WebSite, new { @class = "form-control", @placeholder = "Ej: http://www.helpme-hunter.com" })
                @Html.ValidationMessageFor(m => m.WebSite)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="row">
                <div class="col-xs-8">
                    <div class="form-group form-material ">
                        <label class="control-label">Teléfono</label>
                        @Html.TextBoxFor(m => m.Telefono, new { @class = "form-control input-number", @data_plugin = "formatter", @data_pattern = "(01) [[999]]-[[9999]]" })
                        @Html.ValidationMessageFor(m => m.Telefono)
                    </div>
                </div>
                <div class="col-xs-4">
                    <div class="form-group form-material ">
                        <label class="control-label">Anexo</label>
                        @Html.TextBoxFor(m => m.Anexo, new { @class = "form-control input-number", @data_plugin = "formatter", @data_pattern = "(*) [[9999]]" })
                        @Html.ValidationMessageFor(m => m.Anexo)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿Cuál es tu celular?</label>
                @Html.TextBoxFor(m => m.Celular, new { @class = "form-control input-number", @data_plugin = "formatter", @data_pattern = "9[[99]]-[[999]]-[[999]]" })
                @Html.ValidationMessageFor(m => m.Celular)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿A que país pertenece la empresa?</label>
                @Html.DropDownListFor(m => m.IdPaisEmpresa, Model.Paises, new { @class = "form-control", @data_plugin = "select2" })
                @Html.ValidationMessageFor(m => m.IdPaisEmpresa)
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿A que país perteneces?</label>
                @Html.DropDownListFor(m => m.IdPais, Model.Paises, new { @class = "form-control", @data_plugin = "select2" })
                @Html.ValidationMessageFor(m => m.IdPais)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿Cuáles son tus nombres?</label>
                @Html.TextBoxFor(m => m.Nombres, new { @class = "form-control", @placeholder = "Escribe aquí tus nombres" })
                @Html.ValidationMessageFor(m => m.Nombres)
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿Cuáles son tus apellidos?</label>
                @Html.TextBoxFor(m => m.Apellidos, new { @class = "form-control", @placeholder = "Escribe aquí tus apellidos" })
                @Html.ValidationMessageFor(m => m.Apellidos)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿Cuál es tu puesto actual en la empresa?</label>
                @Html.TextBoxFor(m => m.PuestoActual, new { @class = "form-control", @placeholder = "Selecciona al menos un puesto de trabajo" })
                @Html.ValidationMessageFor(m => m.PuestoActual)
            </div>
        </div>
        <div class="col-sm-6 col-xs-12 text-left">
            <div class="form-group form-material ">
                <label class="control-label">¿Cuál es tu correo corporativo?</label>
                @Html.TextBoxFor(m => m.CorreoCorporativo, new { @class = "form-control", @placeholder = "Ej: roberto@helpme-hunter.com" })
                @Html.ValidationMessageFor(m => m.CorreoCorporativo)
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 text-right">
            <button class="btn btn-primary">
                <i class="icon wb-check" aria-hidden="true"></i>
                Continuar
            </button>
        </div>
    </div>
}

@section ScriptsPlugins {
    <script src="~/remark/plugins/select2/select2.full.min.js"></script>
    <script src="~/remark/plugins/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/remark/plugins/formatter-js/jquery.formatter.min.js"></script>
    <script src="~/remark/js/components/select2.min.js"></script>
    <script src="~/remark/js/components/bootstrap-select.min.js"></script>
    <script src="~/remark/js/components/formatter-js.min.js"></script>
    <script src="~/remark/plugins/typeahead-js/bloodhound.min.js"></script>
    <script src="~/remark/plugins/typeahead-js/typeahead.jquery.min.js"></script>
}
@section Scripts {
    
    <script>
        $('#PuestoActual').typeahead({
            minLength: 1,
            highlight: true
        }, {
            name: 'puestos',
            source: (query, syncResults, asyncResults) => {
                $.getJSON('@Url.Action("ListarPuestos")', { query: query })
                .done((data) => {
                    asyncResults(data);
                });
            }
        })
    </script>

}

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Views/Cuenta/Index.cshtml
@model HelpmeHunter.Presentacion.Landing.ViewModels.Cuenta.IndexVM

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_CuentaLayout.cshtml";
}

@section Styles {
    <style>
        .page-content {
            max-width: 400px;
        }
    </style>
}

@section Modals {
    <div class="modal fade" id="modal-registrarme" aria-hidden="true" role="dialog" tabindex="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                    <h4 class="modal-title" id="exampleModalTabs">¿Cómo deseas registrarte?</h4>
                </div>
                <ul class="nav nav-tabs nav-tabs-line" data-plugin="nav-tabs" role="tablist">
                    <li class="active" role="presentation"><a data-toggle="tab" href="#tabEmpresa" role="tab" aria-expanded="false">Empresa</a></li>
                    <li role="presentation"><a data-toggle="tab" href="#tabConsultor" role="tab" aria-expanded="false">Consultor</a></li>
                    <li role="presentation"><a data-toggle="tab" href="#tabProfesional" role="tab" aria-expanded="false">Profesional</a></li>
                </ul>
                <div class="modal-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="tabEmpresa" role="tabpanel">
                            <p>
                                Insolens patientiamque recte caecilii gaudere alienae varias repetitis inscientia
                                ipsos. Partiendo interpretum vult ludicra iam abest
                                disputatum geometriaque inflammat probes, tandem
                                ullum iuste texit mundus delicatissimi iactare, impeditur
                            </p>
                            <p class="text-right">
                                @Html.ActionLink("Registrarme", "Empresa", null, new { @class = "btn btn-info" })
                            </p>
                        </div>
                        <div class="tab-pane" id="tabConsultor" role="tabpanel">
                            <p>
                                Tenuit omni magistra quale honoris, maluisti invidi, successerit feramus fere omnium
                                impetum locus suscipiantur ullum, gessisse afranius
                                stabilique repellendus longinquitate sentiamus torquatos
                                rem. Bene continens, depulsa soluta domesticarum
                                inscientia excruciant artes epicuri, huic similique
                            </p>
                            <p class="text-right">
                                @Html.ActionLink("Registrarme", "Consultor", null, new { @class = "btn btn-info" })
                            </p>
                        </div>
                        <div class="tab-pane" id="tabProfesional" role="tabpanel">
                            <p>
                                Cernimus nutu. Maioribus solet. Iustitiam conciliant reliquisti instituendarum
                                solido quicquid, superstitione placet illis privatione
                                clariora audeam repellat morbos accusantibus, quaeso
                                copulationes. Percurri salutatus derigatur praeter
                                involuta canes afflueret iam amotio quin. Dicent
                                dialectica evertunt astris venire senserit. Vulgo
                            </p>
                            <p class="text-right">
                                @Html.ActionLink("Registrarme", "Profesional", null, new { @class = "btn btn-info" })
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<h5 class="text-left">Ingresa a HELPME-HUNTER</h5>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <button type="button" class="btn btn-block btn-labeled social-linkedin" name="@Html.NameFor(m => m.EsEmpresa)" value="false">
        <span class="btn-label">
            <i class="icon bd-linkedin" aria-hidden="true"></i>
        </span>
        Linkedin
    </button>
}
<div class="separator"></div>
<h5 class=" text-left">Ó ingresa como empresa</h5>
@using (Html.BeginForm())
{
    Model.EsEmpresa = true;
    @Html.HiddenFor(m => m.EsEmpresa)
    @Html.AntiForgeryToken()
    <div class="form-group text-left">
        <div class="input-group input-group-icon">
            @Html.TextBoxFor(m => m.Correo, new { @class = "form-control", @placeholder = "Escribe tu correo aquí", @maxlength = 100 })
            <span class="input-group-addon">
                <span class="icon wb-envelope" aria-hidden="true"></span>
            </span>
        </div>
        @Html.ValidationMessageFor(m => m.Correo)
    </div>
    <div class="form-group text-left">
        <div class="input-group input-group-icon">
            @Html.PasswordFor(m => m.Clave, new { @class = "form-control", @placeholder = "Escribe tu clave aquí", @maxlength = 20 })
            <span class="input-group-addon">
                <span class="icon wb-lock" aria-hidden="true"></span>
            </span>
        </div>
        @Html.ValidationMessageFor(m => m.Clave)
    </div>
    <button class="btn btn-primary btn-block">
        Entrar
    </button>
}
<div class="separator"></div>
<a href="#" data-target="#modal-registrarme" data-toggle="modal">
    ¡No tengo cuenta y quiero registrarme!
</a>

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Views/Home/Contacto.cshtml
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url(@Url.Content("~/Content/images/img_bg_2.jpg"));">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <div class="display-t">
                    <div class="display-tc animate-box" data-animate-effect="fadeIn">
                        <h1>Contact Us</h1>
                        <h2>Free html5 templates Made by <a href="http://freehtml5.co" target="_blank">freehtml5.co</a></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="fh5co-section">
    <div class="container">
        <div class="row">
            <div class="col-md-6 animate-box">
                <h3>Get In Touch</h3>
                <form action="#">
                    <div class="row form-group">
                        <div class="col-md-6">
                            <!-- <label for="fname">First Name</label> -->
                            <input type="text" id="fname" class="form-control" placeholder="Your firstname">
                        </div>
                        <div class="col-md-6">
                            <!-- <label for="lname">Last Name</label> -->
                            <input type="text" id="lname" class="form-control" placeholder="Your lastname">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <!-- <label for="email">Email</label> -->
                            <input type="text" id="email" class="form-control" placeholder="Your email address">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <!-- <label for="subject">Subject</label> -->
                            <input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <!-- <label for="message">Message</label> -->
                            <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Send Message" class="btn btn-primary">
                    </div>
                </form>
            </div>
            <div class="col-md-5 col-md-push-1 animate-box">

                <div class="fh5co-contact-info">
                    <h3>Contact Information</h3>
                    <ul>
                        <li class="address">198 West 21th Street, <br> Suite 721 New York NY 10016</li>
                        <li class="phone"><a href="tel://1234567920">+ 1235 2355 98</a></li>
                        <li class="email"><a href="mailto:info@yoursite.com">info@yoursite.com</a></li>
                        <li class="url"><a href="http://FreeHTML5.co">FreeHTML5.co</a></li>
                    </ul>
                </div>
            </div>
        </div>

    </div>
</div>
<div id="fh5co-started">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2>Newsletter</h2>
                <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
            </div>
        </div>
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2">
                <form class="form-inline">
                    <div class="col-md-6 col-sm-6">
                        <div class="form-group">
                            <label for="email" class="sr-only">Email</label>
                            <input type="email" class="form-control" id="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="col-md-6 col-sm-6">
                        <button type="submit" class="btn btn-default btn-block">Subscribe</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Views/Shared/_BasicStyles.cshtml
<!-- Fonts -->
<link href="~/remark/fonts/web-icons/web-icons.min09a2.css?v2.1.0" rel="stylesheet" />
<link href="~/remark/fonts/brand-icons/brand-icons.min09a2.css?v2.1.0" rel="stylesheet" />
<link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic'>

<!-- stylesheets -->

<link href="~/remark/css/bootstrap.min09a2.css?v2.1.0" rel="stylesheet" />
<link href="~/remark/css/bootstrap-extend.min09a2.css?v2.1.0" rel="stylesheet" />
<link href="~/remark/css/site.min09a2.css?v2.1.0" rel="stylesheet" />

<!-- Plugins -->
<link href="~/remark/plugins/animsition/animsition.min09a2.css" rel="stylesheet" />
<link href="~/remark/plugins/asscrollable/asScrollable.min09a2.css" rel="stylesheet" />
<link href="~/remark/plugins/switchery/switchery.min09a2.css" rel="stylesheet" />
<link href="~/remark/plugins/intro-js/introjs.min09a2.css" rel="stylesheet" />
<link href="~/remark/plugins/slidepanel/slidePanel.min09a2.css" rel="stylesheet" />
<link href="~/remark/plugins/flag-icon-css/flag-icon.min09a2.css" rel="stylesheet" />



<!-- Scripts -->
<script src="~/remark/plugins/modernizr/modernizr.min.js"></script>
<script src="~/remark/plugins/breakpoints/breakpoints.min.js"></script>

HelpmeHunter/HelpmeHunter.Presentacion.Landing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>HelpmeHunter</title>

    @Styles.Render("~/css")

    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.min.js")"></script>
    <!--[if lt IE 9]>
    <script src="@Url.Content("~/Scripts/respond.min.js")"></script>
    <![endif]-->

</head>
<body>
    <div class="fh5co-loader"></div>

    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="container">
                <div class="row">
                    <div class="col-xs-2">
                        <div id="fh5co-logo"><a href="@Url.Action("Index")">Bow.</a></div>
                    </div>
                    <div class="col-xs-10 text-right menu-1">
                        <ul>
                            <li class="active">@Html.ActionLink("Home", "Index")</li>
                            <li>@Html.ActionLink("About", "Acerca")</li>
                            <li class="has-dropdown">
                                @Html.ActionLink("Services", "Servicios")
                                <ul class="dropdown">
                                    <li><a href="#">Web Design</a></li>
                                    <li><a href="#">eCommerce</a></li>
                                    <li><a href="#">Branding</a></li>
                                    <li><a href="#">API</a></li>
                                </ul>
                            </li>
                            <li class="has-dropdown">
                                <a href="#">Tools</a>
                                <ul class="dropdown">
                                    <li><a href="#">HTML5</a></li>
                                    <li><a href="#">CSS3</a></li>
                                    <li><a href="#">Sass</a></li>
                                    <li><a href="#">jQuery</a></li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Work", "Trabajo")</li>
                            <li>@Html.ActionLink("Contact", "Contacto")</li>
                            <li>@Html.ActionLink("Soy profesional", "Profesional", "Cuenta", null, new { @class = "btn btn-info", @style = "padding: 5px 10px; border-radius: 4px; text-transform:capitalize;" })
                            <li>@Html.ActionLink("Ingresar", "Index", "Cuenta", null, new { @class = "btn btn-info", @style = "padding: 5px 10px; border-radius: 4px; text-transform:capitalize;" })
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </nav>

        @RenderBody()

        <footer id="fh5co-footer" role="contentinfo">
            <div class="container">
                <div class="row row-pb-md">
                    <div class="col-md-4 fh5co-widget">
                        <h3>The Company</h3>
                        <p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
                        <p><a href="#">Learn More</a></p>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                        <ul class="fh5co-footer-links">
                            <li><a href="#">About</a></li>
                            <li><a href="#">Help</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Terms</a></li>
                            <li><a href="#">Meetups</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                        <ul class="fh5co-footer-links">
                            <li><a href="#">Shop</a></li>
                            <li><a href="#">Privacy</a></li>
                            <li><a href="#">Testimonials</a></li>
                            <li><a href="#">Handbook</a></li>
                            <li><a href="#">Held Desk</a></li>
                        </ul>
                    </div>
                    <div class="col-md-2 col-sm-4 col-xs-6 col-md-push-1">
                        <ul class="fh5co-footer-links">
                            <li><a href="#">Find Designers</a></li>
                            <li><a href="#">Find Developers</a></li>
                            <li><a href="#">Teams</a></li>
                            <li><a href="#">Advertise</a></li>
                            <li><a href="#">API</a></li>
                        </ul>
                    </div>
                </div>
                <div class="row copyright">
                    <div class="col-md-12 text-center">
                        <p>
                            <small class="block">&copy; 2016 Free HTML5. All Rights Reserved.</small>
                            <small class="block">Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Demo Images: <a href="http://unsplash.co/" target="_blank">Unsplash</a></small>
                        </p>
                        <p>
                            <ul class="fh5co-social-icons">
                                <li><a href="#"><i class="icon-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-linkedin"></i></a></li>
                                <li><a href="#"><i class="icon-dribbble"></i></a></li>
                            </ul>
                        </p>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    @Scripts.Render("~/js")
</body>
</html>